language: rust
rust:
    - stable
    - nightly

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test

before_install:
    - sudo add-apt-repository -y ppa:beineri/opt-qt-5.10.1-trusty;
    - sudo apt-get update

install:
    - sudo apt-get install -y -qq qt510base qt510declarative g++-7
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90;

before_script:
    - source /opt/qt510/bin/qt510-env.sh
    - export RUST_TEST_THREADS=1

script:
    - (cd qmetaobject && xvfb-run cargo test -- --test-threads=1)
    - (cd examples/todos && cargo build)
    - (cd examples/qmlextensionplugins && cargo build)
    - (cd examples/graph && cargo build)
