[package]
name = "qmetaobject"
version = "0.1.0"
authors = ["Olivier Goffart <ogoffart@woboq.com>"]
build = "build.rs"

[dependencies]
cpp = { path = "/home/rust/rust-cpp/cpp"}
qmetaobject_impl = { path = "../qmetaobject_impl"}
lazy_static = "1.0"


[build-dependencies]
cpp_build = { path = "/home/rust/rust-cpp/cpp_build"}

