[package]
name = "qmetaobject_impl"
version = "0.1.0"
authors = ["Olivier Goffart <ogoffart@woboq.com>"]

[lib]
proc-macro = true

[dependencies]
syn = "0.12"
quote = "0.4"
proc-macro-hack = "0.4"
synstructure = "0.7"
